chatterbot/apis/twitter.py, readme.md, requirements.txt, tests/test_twitter.py
This fixes incompatibilities with python3 by removing the `python-oauth2` library in favor of `requests-oauthlib`.
This also changes the oauth workflow to make it possible to redirect request urls to third party apps.
Closes #16
=> Fixes twitter oauth features

chatterbot/adapters/io/__init__.py, chatterbot/adapters/io/no_output.py, tests/io_adapter_tests/test_no_output_adapter.py
The new adapter allows the user to get a response from the chat bot without having that response displayed ( in the terminal, for example ).
=> Added no output adapter

chatterbot/adapters/storage/__init__.py, chatterbot/adapters/storage/jsondatabase.py, chatterbot/adapters/storage/mongodb.py, chatterbot/adapters/storage/storage.py
This change is to maintain consistency with the name of this module (`chatterbot.adapters.storage`).
In the future, I also feel that the term _storage_ is more flexible then the term _database_. In the future, it is possible that there may be non-database storage sources.
=> Renamed DatabaseAdapter to StorageAdapter

chatterbot/adapters/storage/jsondatabase.py, chatterbot/chatterbot.py, tests/storage_adapter_tests/test_jsondb_adapter.py, tests/test_chatbot_output.py, tests/training_tests/test_training.py
This corrects an issue for cases where no statements exist that are in response to the closest matching statement. This previously resulted in a case where a matching response could not be found and caused a random response to be returned.
Closes #71
Closes #72
=> Prevent statements that are not in response to a known statement from being passed to the logic adapter.

chatterbot/adapters/logic/closest_meaning.py
TypeError: __init__() got an unexpected keyword argument 'logic_adapter because chatterbot.py initializes the logic adapters with his kwargs. The Closestmatch adapter uses the __init__() from logic.py
=> ClosestMeaningAdapter wasn't useable

chatterbot/adapters/storage/mongodb.py, tests/storage_adapter_tests/test_jsondb_adapter.py, tests/storage_adapter_tests/test_mongo_adapter.py
Response objects were being returned from the mongo storage adapter as dictionaries instead of Response object lists. This was happening because the conversion method was not being called to normalize the results before they were returned.
=> Correct issue with response objects using mongo storage adapter

chatterbot/adapters/storage/__init__.py, chatterbot/adapters/storage/twitter_storage.py, examples/twitter_storage_example.py, requirements.txt
This creates a storage adapter that uses twitter's API as a fake storage endpoint to search and retrieve public tweets from.
https://dev.twitter.com/oauth/application-only
Related: #15
=> Added storage adapter that reads tweets from twitter api

chatterbot/adapters/adaptation.py, chatterbot/adapters/logic/__init__.py, chatterbot/adapters/logic/base_match.py, chatterbot/adapters/logic/logic.py, chatterbot/adapters/logic/multi_adapter.py, chatterbot/adapters/logic/no_knowledge_adapter.py, chatterbot/chatterbot.py, tests/test_adaptation.py
This moves a section of code in `chatterbot.py` that handles the case that no responses exist in the database to its own logic adapter. The new logic adapter will always be set as the first logic adapter in the list so that it takes priority over each of the other logic adapters.
=> Added system adapter for case when database is empty

chatterbot/adapters/logic/evaluate_mathematically.py, chatterbot/adapters/logic/time_adapter.py, examples/terminal_example.py
Just a couple of minor changes, including:
1) Add additional logic adapters to the terminal example adding functionality
2) Possible bug fix in evaluate_mathematically (not really sure, but this makes sure no bug will ever arise)
3) Sometimes, the time logic adapter would find a statement similar to "what is 100 * 10?" as something it should process. By adding the additional piece of training data, the time adapter does not incorrectly process math statements as often
=> minor fixes in logic adapters & terminal example

chatterbot/adapters/logic/closest_match.py, tests/logic_adapter_tests/test_closest_match.py
This updates and adds tests to ensure that the confidence value returned by the closest match adapter fall within the range between 0 and 1.
=> Make sure that closest match adapter confidence returns value between 0 and 1

chatterbot/adapters/io/__init__.py, chatterbot/adapters/io/tts.py, tests/io_adapter_tests/test_tts.py
I added an io adapter for a TTS engine built in to MacOSX.
Although I added an output adapter, I have not added a corresponding STT adapter so it gets input using the Terminal. I recommend we make a change to the way io adapters are structured (which will also solve the problem with multiple inputs in my other PR), separating out input adapters and output adapters. This way, the user can specify more precisely what they would like to use for inputs and outputs. @gunthercox What do you think?
=> Add a MacOSX TTS io adapter

chatterbot/adapters/storage/jsondatabase.py, chatterbot/adapters/storage/mongodb.py, chatterbot/adapters/storage/storage.py, chatterbot/conversation/statement.py, tests/conversation_tests/test_statements.py, tests/storage_adapter_tests/integration_tests/mongo_integration_tests.py, tests/storage_adapter_tests/test_jsondb_adapter.py, tests/storage_adapter_tests/test_mongo_adapter.py
In the case that a statement needs to be removed from a database, this pull request adds the ability to do so.
Closes #126
The removal of a statement with the text `"Decepticons forever!"` would be executed as follows:
```python
chatbot = ChatBot("Optimus")
chatbot.storage.remove("Decepticons forever!")
```
=> Add method for removing a statement

chatterbot/adapters/logic/closest_meaning.py
This helps the closest meaning logic adapter to select an accurate match by getting the closest path combination for all possible combinations of synsets.
Closes #65
=> Select the closest pair of synsets for two words

chatterbot/adapters/logic/__init__.py, chatterbot/adapters/logic/mathematical_evaluation.py, docs/tutorial.rst, examples/math_and_time.py, examples/terminal_example.py, tests/logic_adapter_tests/test_evaluate_mathematically.py
:rocket: This is just a rename for aesthetic purposes. "MathematicalEvaluation adapter" rolls off the tongue a bit better.
=> Rename EvaluateMathematically logic adapter to MathematicalEvaluation

chatterbot/chatterbot.py, chatterbot/utils/queues.py, tests/test_chatbot.py, tests/test_queues.py
Closes #132
Related to avoiding repetitions for #148
=> Redesign recent_statements to hold the entire current conversation

chatterbot/adapters/storage/mongodb.py
Add deserialize_responses call to mongo adapter get_response_statemets realization to prevent AttributeError: 'dict' object has no attribute 'serialize' in response.serialize().
```python
Traceback (most recent call last):
File "examples/terminal_mongo_example.py", line 19, in <module>
bot_input = bot.get_response(None)
File "/Users/timofey/Projects/ChatterBot/chatterbot/chatterbot.py", line 136, in get_response
confidence, response = self.logic.process(input_statement)
File "/Users/timofey/Projects/ChatterBot/chatterbot/adapters/logic/multi_adapter.py", line 27, in process
confidence, output = adapter.process(statement)
File "/Users/timofey/Projects/ChatterBot/chatterbot/adapters/logic/base_match.py", line 47, in process
self.context.storage.update(closest_match)
File …
```
=> Fix mongo adapter get_response_statemets method

chatterbot/adapters/input/__init__.py, chatterbot/adapters/input/hipchat.py, chatterbot/adapters/output/__init__.py, chatterbot/adapters/output/hipchat.py, docs/adapters/input.rst, docs/adapters/output.rst, examples/hipchat_bot.py
This adds input and output adapters that allow ChatterBot to communicate through [HipChat's](https://www.hipchat.com/) API.
=> Add HipChat input and output adapter

chatterbot/adapters/storage/mongodb.py
This changes the Mongo DB storage adapter so that it applies bulk operations when updating statements.
=> Use bulk operations in mongo update method

chatterbot/corpus/corpus.py
Diacritics did not work with Croatian corpus and I think it should help with other languages as well. I am planning to create a pull request for Croatian corpus as well these days.
=> Added UTF-8 support in corpus

chatterbot/adapters/logic/base_match.py, chatterbot/adapters/logic/closest_match.py, chatterbot/chatterbot.py, chatterbot/conversation/statement.py, chatterbot/corpus/corpus.py, tests/conversation_tests/test_statements.py, tests/training_tests/test_list_training.py
Closes #215
Related https://github.com/seatgeek/fuzzywuzzy/issues/129
This corrects a few of the unicode string errors that were occurring in ChatterBot. The main issue was that a redundant check for an exact string match was being made. This has been removed and a more unicode-friendly implementation of the fuzzy matching functionality for statements is now being used.
=> Correct unicode equality issue in python 2.7

chatterbot/chatterbot.py, chatterbot/trainers.py, docs/training.rst, examples/export_example.py, tests/training_tests/test_database_export.py, tests/training_tests/test_training.py
=> Add ability to export database as ChatterBot training corpus

chatterbot/adapters/logic/base_match.py, tests/logic_adapter_tests/test_closest_match.py
In the base class for the matching adapters, if no possible responses to the input are known then a random response is chosen from the database. This needed to be changed so that if so that if a random response is selected, a confidence value of zero is returned.
Closes #243
=> Return a confidence of zero if a random response is selected

chatterbot/adapters/storage/mongodb.py
count = self.count()
random_integer = randint(0, count - 1)    #l2
if self.count() < 1:
raise self.EmptyDatabaseException()
if count is less than 1, then #2 will result in valueError
```
In [5]: count  = 0
In [6]: random.randint(0, count-1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-ab1e1b11223b> in <module>()
----> 1 random.randint(0, count-1)
/usr/lib/python2.7/random.pyc in randint(self, a, b)
240         """
241 
--> 242         return self.randrange(a, b+1)
243 
244     def _randbelow(self, n, _log=_log, _int=int, _maxwidth=1L<<BPF,
/usr/lib/python2.7/random.pyc in randrange(self, start, stop, step, _int, _maxwidth)
216             return _int(istart + …
```
=> count check before its use

readme.md
I have created a [simple Flask app using ChatterBot](https://github.com/chamkank/flask-chatterbot) that would be a great starter template for anyone who uses Flask instead of Django. So I thought it might be helpful to leave a link to it alongside the Django example in the readme.
I will also add 2 more patches for the other readme files (in different languages) if this patch is accepted.
=> Adding Flask Example Link to English ReadMe

readme-es.md
Added Flask project link in this final readme. (see [https://github.com/gunthercox/ChatterBot/pull/250](https://github.com/gunthercox/ChatterBot/pull/250) first).
=> Adding Flask Example Link to readme-es.md

readme.pt.md
Added Flask project link in this readme. (see [https://github.com/gunthercox/ChatterBot/pull/250](https://github.com/gunthercox/ChatterBot/pull/250) first).
=> Adding Flask Example Link to readme.pt.md

.gitignore, chatterbot/chatterbot.py
See #262 for details.  Small patch to pass through extra_data from the original input statement.  This is useful for knowing where/how to respond, who asked the original question, etc.
=> #262 fix: Pass through existing extra data from the input

chatterbot/adapters/logic/__init__.py, chatterbot/adapters/logic/approximate_sentence_match.py, docs/adapters/logic.rst
Jaccard index is found to have better performance in  approximate sentence matching so implement it.
=> approximate sentence match logic adapter and its docs 

chatterbot/chatterbot.py, tests/base_case.py, tests/test_chatbot.py, tests/training_tests/test_list_training.py
=> Test strings

chatterbot/adapters/logic/time_adapter.py
It looks like `"do you know the time"` was accidentally added to both the "hit" and "miss" lists. This commit ensures it's classified as a match.
=> Improve the Bayes classifier in time_adapter.py

chatterbot/adapters/logic/__init__.py, chatterbot/adapters/logic/sentiment_adapter.py, docs/adapters/logic.rst, tests/logic_adapter_tests/test_sentiment.py
The goal of this adapter is to allow the chat bot to respond to input based on the level of sentiment that the input contains.
Recreation of #167
Closes #7
=> Add a sentiment selection based logic adapter

chatterbot/adapters/logic/approximate_sentence_match.py, chatterbot/adapters/logic/base_match.py, chatterbot/adapters/logic/closest_match.py, chatterbot/adapters/logic/closest_meaning.py, chatterbot/conversation/comparisons.py
Logic adapters should use the comparison method passed to the chat bot. This should simplify and reduce the amount of code that needs to be written to create text-matching style logic adapters.
=> Move logic adapter statement comparison methods to their own module

chatterbot/adapters/logic/approximate_sentence_match.py, chatterbot/conversation/comparisons.py
Incorrect class name
````
super(ClosestMatchAdapter, self).__init__(**kwargs)
NameError: global name 'ClosestMatchAdapter' is not defined
````
=> Fix init class name

chatterbot/adapters/storage/django_storage.py, chatterbot/adapters/storage/jsonfile.py, chatterbot/adapters/storage/mongodb.py, chatterbot/trainers.py
This is just a proposal. 
Scenario
Most of my clients want a training corpora but they dont want bots to auto-learn.
So when i am starting up the bot
````
bot = ChatBot('name', read_only=True)
bot.train('english') # Add corpus even if read_only is True
````
What do you think?
=> Force training even if read_only is True

.gitignore, chatterbot/utils/stop_words.py, chatterbot/utils/tokenizer.py, chatterbot/utils/wordnet.py
https://github.com/gunthercox/ChatterBot/issues/350
=> nltk_data download loop

chatterbot/adapters/logic/multi_adapter.py, chatterbot/conversation/response.py, chatterbot/conversation/statement.py, tests/logic_adapter_tests/test_multi_adapter.py
=> Add check for logic adapter agreement

chatterbot/adapters/logic/base_match.py, chatterbot/adapters/logic/closest_match.py, chatterbot/adapters/logic/closest_meaning.py, chatterbot/conversation/comparisons.py, tests/logic_adapter_tests/test_closest_meaning.py
This pull request makes two changes:
1. This makes changes to the function so that it will return a percent of similarity between the two statements it takes as parameters. By returning a percent it makes the output of this function easier to
compare to the output of other comparison functions.
2. By normalizing the output from the statement comparison functions, it allows redundant code in the statement matching adapters to be combined.
=> Modify synset_distance comparison function

chatterbot/adapters/logic/sentiment_adapter.py, chatterbot/conversation/comparisons.py
This allows the sentiment matching adapter to be simplified.
This is related to the changes made in #385.
=> Move sentiment matching to it's own function

chatterbot/adapters/logic/approximate_sentence_match.py
This removed redundant code from the `ApproximateSentenceMatchAdapter`.
=> Don't overide get method on ApproximateSentenceMatchAdapter

chatterbot/chatterbot.py, docs/chatterbot.rst, tests/test_adapter_validation.py, tests/test_initialization.py
This adds a backwards compatible method for setting parameters for specific adapters.
Closes #287
=> Add ability to set per-adapter parameters

chatterbot/corpus/data/italian/math_words.json, chatterbot/corpus/data/italian/swear_words.csv, readme.it.md
Created the italian readme and  first drafts of the italian math and swear words dictionaries.
=> Updated Italian corpus with math and swear words

chatterbot/__init__.py, chatterbot/adapters/input/__init__.py, chatterbot/adapters/input/microsoft.py, chatterbot/adapters/output/__init__.py, chatterbot/adapters/output/microsoft.py, docs/adapters/input.rst, docs/adapters/output.rst, examples/microsoft_bot.py, tests/input_adapter_tests/test_microsoft_input_adapter.py, tests/output_adapter_tests/test_microsoft_output_adapter.py
Closes https://github.com/gunthercox/ChatterBot/issues/290
=> Integration with Microsoft Bot Framework

chatterbot/conversation/comparisons.py, requirements.txt
This change is being made to increase the level of control that we have over the string matching process in this method. This also simplifies the statement comparison algorithm that ChatterBot uses in this function so that logging is possible and debugging is easier.
=> Remove dependency on fuzzywuzzy

.gitignore, chatterbot/trainers.py, docs/training.rst, examples/ubuntu_corpus_training_example.py, tests/training_tests/test_ubuntu_corpus_training.py
- **Functions for managing Ubuntu data corpus**
Closes #382
=> Add training class for Ubuntu corpus

chatterbot/adapters/adapter.py, chatterbot/adapters/input/hipchat.py, chatterbot/adapters/input/input_adapter.py, chatterbot/adapters/logic/base_match.py, chatterbot/adapters/logic/multi_adapter.py, chatterbot/adapters/logic/no_knowledge_adapter.py, chatterbot/adapters/output/hipchat.py, chatterbot/chatterbot.py, docs/adapters/index.rst, tests/input_adapter_tests/test_input_adapter.py, tests/logic_adapter_tests/test_closest_match.py, tests/logic_adapter_tests/test_closest_meaning.py, tests/logic_adapter_tests/test_data_cache.py, tests/logic_adapter_tests/test_low_confidence_adapter.py, tests/logic_adapter_tests/test_multi_adapter.py, tests/logic_adapter_tests/test_sentiment.py, tests/test_context.py
This variable is being renamed to help stop developers from being confused. The new name is more accurate and better describes what the content of the variable actually is.
Closes #281
=> Rename 'context' to 'chatbot'

chatterbot/chatterbot.py, chatterbot/conversation/__init__.py, chatterbot/conversation/session.py, chatterbot/ext/django_chatterbot/views.py, chatterbot/filters.py, chatterbot/output/gitter.py, chatterbot/output/hipchat.py, chatterbot/output/mailgun.py, chatterbot/output/microsoft.py, chatterbot/output/output_adapter.py, chatterbot/output/output_format_adapter.py, chatterbot/output/terminal.py, chatterbot/queues.py, chatterbot/storage/storage_adapter.py, docs/index.rst, docs/sessions.rst, docs/utils.rst, examples/django_app/tests/test_integration.py, examples/learning_feedback_example.py, tests/filter_integration_tests/test_filters_with_mongo_storage.py, tests/test_chatbot.py, tests/test_context.py, tests/test_queues.py, tests/test_sessions.py
=> Add session management

chatterbot/__init__.py, chatterbot/input/gitter.py, chatterbot/input/hipchat.py, chatterbot/input/mailgun.py, chatterbot/input/microsoft.py, chatterbot/logic/time_adapter.py, chatterbot/output/gitter.py, chatterbot/output/hipchat.py, chatterbot/output/mailgun.py, chatterbot/output/microsoft.py, chatterbot/storage/jsonfile.py, chatterbot/storage/mongodb.py
In some cases, having these packages imported on the global level caused errors during the installation process. This is because some ChatterBot classes are imported in `__init__.py` files and the main `__init__.py` in the chatterbot module is imported by setup.py. As a result, the external packages are imported before
they get installed.
Closes #425
=> Update scope of external package imports

chatterbot/chatterbot.py, chatterbot/logic/multi_adapter.py, chatterbot/utils.py, tests/logic_adapter_tests/test_multi_adapter.py, tests/test_adapter_validation.py, tests/test_initialization.py
The MultiLogicAdapter which handles the process of checking the generated responses of other logic adapters, could return just the user's input if other logic adapters are added after the chat bot is initialized. This was fixed by adding a separate list for system logic adapters that are required to be present at all times.
Closes #431
=> Prevent possible edge case when adding inserting logic adapters

chatterbot/logic/mathematical_evaluation.py, tests/logic_adapter_tests/test_mathematical_evaluation.py
The changes are:
- added support for **mathematical constants and** some numpy **functions** (closes #320)
- some **refactoring** of the chunk processing (nested `if`/`else` statements)
- **separating words** using a operators rather than spaces (allowing strings such as `"log(3+4)"` to be processed, instead of just `"log ( 3 + 4 ) "`)
I hope this is in keeping with coding standards of the project, especially the addition of a class attribute (`functions` in `MathematicalEvaluation`). Also, there could be more [math functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html) and [constants](https://en.wikipedia.org/wiki/Mathematical_constant#Table_of_selected_mathematical_constants).
=> New math operations

chatterbot/logic/mathematical_evaluation.py
This makes changes so that if a value is processed by the 'can_process' method of the math adapter, the
result can be reused when the 'process' method is called. This reduces redundant operations and increases the efficiency of this method.
=> Cache results from can_process method in math adapter

chatterbot/conversation/session.py, chatterbot/ext/django_chatterbot/views.py, examples/django_app/tests/test_views.py, tests/test_sessions.py
This fixes a problem where a chat id could be provided, but a chat session for it did not exist.
Closes #453
=> Handle the case that a chat session does not exist

chatterbot/logic/best_match.py, tests/base_case.py, tests/logic_adapter_tests/best_match_integration_tests/test_levenshtein_distance.py, tests/logic_adapter_tests/best_match_integration_tests/test_synset_distance.py, tests/logic_adapter_tests/test_best_match.py, tests/logic_adapter_tests/test_low_confidence_adapter.py
This method is no longer needed. A simple check for the number of statements serves the same purpose.
=> Remove 'has_storage' method

chatterbot/conversation/statement.py
Doing this update from the remaining kwargs entails confusing functionality of the statement arguments. Removing this line and having `extra_data` set explicitly is better than having it implicitly gain any left over kwargs.
=> Do not update extra data from kwargs

docs/django/index.rst
Executing migrate thorws error when follows Chatterbot Django docs.  Django migrate needs `app_label`. So I updated the docs. 
Actual Error
```
$ python manage.py migrate chatterbot.ext.django_chatterbot
CommandError: App 'chatterbot.ext.django_chatterbot' does not have migrations.
```
=> App label is enough for migrate

chatterbot/chatterbot.py, chatterbot/ext/django_chatterbot/settings.py, chatterbot/ext/django_chatterbot/views.py, chatterbot/output/output_adapter.py, chatterbot/output/output_format_adapter.py, examples/math_and_time.py, examples/tkinter_gui.py, tests/base_case.py, tests/output_adapter_tests/test_output_adapter.py, tests/test_initialization.py
This removes the need to replicate basic methods and properties that are available on the statement object. The `OutputFormatAdapter` will eventually be removed.
=> Deprecate OutputFormatAdapter

chatterbot/ext/django_chatterbot/views.py, tests_django/test_api.py
Somehow the current djanog response isn't converting into JSON object, it always returns. https://github.com/gunthercox/ChatterBot/issues/497 issue will fix this error.
=> response into JSON object

chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, tests/storage_adapter_tests/test_json_file_storage_adapter.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_storage_adapter.py, tests_django/test_django_adapter.py
This removes a strange constraint that was being enforced in tests. For some reason response objects were being expected for parts of values in storage adapter filter methods. This pull request removes those constraints because simpler variable types should used to help make storage adapters simpler.
=> Remove tested constraint for response objects in filter method

chatterbot/chatterbot.py, chatterbot/conversation/session.py, docs/sessions.rst, tests/test_sessions.py
Because this class is just used internally, it should be safe to rename without any issues. The name change is being made to make the class name more descriptive.
=> Rename SessionManager to ConversationSessionManager

chatterbot/chatterbot.py, chatterbot/conversation/statement.py, chatterbot/storage/jsonfile.py, chatterbot/storage/mongodb.py, chatterbot/storage/storage_adapter.py
Calling `.save()` should be more intuitive than passing the statement to the update method of the storage adapter.
=> Add save method to statements

chatterbot/conversation/comparisons.py, chatterbot/conversation/response_selection.py
In this future these two files will be removed completely. For now, imports will continue to work to support backwards compatibility.
=> Add warnings about module rename

chatterbot/chatterbot.py, chatterbot/utils.py
`nltk_download_corpus` always downloads nltk resources even if it's already there.
It's because neither `nltk.data.find('stopwords.zip')` nor `nltk.data.find('stopwords')` finds the resource. Maybe `nltk_data` directory tree was flat at some point in the past, but right now it gets populated like this: 
```bash
- corpora
|- stopwords
|- stopwords.zip
|- wordnet
|- wordnet.zip
- sentiment
|- vader_lexicon.zip
- tokenizers
|- punkt
|- punkt.zip
```
and so only a call like `nltk.data.find('corpora/stopwords')` works.
=> nltk.data.find argument needs to be a path, not just a filename

chatterbot/chatterbot.py, chatterbot/storage/storage_adapter.py, chatterbot/utils.py
This makes a change to separate the storage adapter from the base Adapter class. This is being done because the methods on the base Adapter class are not needed on the storage adapter.
The main change is that is no longer possible for the storage adapter to access the ChatBot instance. This should not cause any problems because there are no "known" use cases where this is needed.
This also allows a special case to be removed in the class validation utility so that a check to the "Adapter" class is never made. This allows the class validation utility to be more generic.
=> Disconnect storage from adapter class

chatterbot/conversation/statement.py, chatterbot/ext/django_chatterbot/models.py, chatterbot/logic/best_match.py, chatterbot/logic/low_confidence.py, chatterbot/logic/mathematical_evaluation.py, chatterbot/logic/multi_adapter.py, chatterbot/logic/no_knowledge_adapter.py, chatterbot/logic/specific_response.py, chatterbot/logic/time_adapter.py, docs/conversations.rst, tests/logic_adapter_tests/best_match_integration_tests/test_levenshtein_distance.py, tests/logic_adapter_tests/best_match_integration_tests/test_sentiment_comparison.py, tests/logic_adapter_tests/best_match_integration_tests/test_synset_distance.py, tests/logic_adapter_tests/test_low_confidence_adapter.py, tests/logic_adapter_tests/test_mathematical_evaluation.py, tests/logic_adapter_tests/test_multi_adapter.py, tests/logic_adapter_tests/test_specific_response.py, tests/logic_adapter_tests/test_time.py, tests_django/integration_tests/test_logic_adapter_integration.py
=> Return confidence value on statement object

docs/corpus.rst, docs/encoding.rst, docs/examples.rst, docs/index.rst, docs/logic/create-a-logic-adapter.rst, docs/setup.rst, docs/tutorial.rst, examples/export_example.py
This pull request makes some general improvements to the documentation.
Closes #543
Closes #562
=> Add more examples and expand tutorial in documentation

tests_django/test_api.py, tests_django/test_api_view.py, tests_django/test_django_adapter.py
The confidence value should never be stored in the database, it is just a temporary value that gets returned with the statement.
=> Add regression test to make sure confidence does not get stored in database

chatterbot/comparisons.py
I believe this if statement was meant to check conformity both arguments of the levenshtein_distance() function.
=> fixed argument in levenshtein

chatterbot/chatterbot.py
This fixes a bug with the assignment of the filters attribute, whereby a
generator, rather than it's result is assigned to the ChatBot.filters
attribute. Subsequent iterations of the attribute will return an empty
result.
This fix just assigns the result to the filters attribute as a tuple.
=> Fix "empty generator" bug in ChatBot.filters

chatterbot/corpus/data/english/ai.corpus.json, chatterbot/corpus/data/english/botprofile.corpus.json, chatterbot/corpus/data/english/emotion.corpus.json, chatterbot/corpus/data/english/food.corpus.json, chatterbot/corpus/data/english/history.corpus.json, tests/test_parsing.py
Update for #516, fixes everything pointed out by @gunthercox
=> Some minor text changes

.travis.yml, examples/basic_example.py, examples/tests/readme.md, examples/tests/smoke_tests.py
This adds basic smoke tests. Not all of the examples can be tested against at this point. Explanations have been provided for examples that cannot be tested.
Closes #559
=> Add tests for examples

chatterbot/chatterbot.py, chatterbot/logic/best_match.py, chatterbot/logic/logic_adapter.py, chatterbot/logic/low_confidence.py, chatterbot/logic/mathematical_evaluation.py, chatterbot/logic/multi_adapter.py, chatterbot/logic/no_knowledge_adapter.py, chatterbot/logic/specific_response.py, chatterbot/logic/time_adapter.py, tests/logic_adapter_tests/best_match_integration_tests/test_levenshtein_distance.py, tests/logic_adapter_tests/best_match_integration_tests/test_sentiment_comparison.py, tests/logic_adapter_tests/best_match_integration_tests/test_synset_distance.py, tests/logic_adapter_tests/test_data_cache.py, tests/logic_adapter_tests/test_logic_adapter.py, tests/logic_adapter_tests/test_low_confidence_adapter.py, tests/logic_adapter_tests/test_mathematical_evaluation.py, tests/logic_adapter_tests/test_multi_adapter.py, tests/logic_adapter_tests/test_specific_response.py, tests/logic_adapter_tests/test_time.py, tests_django/integration_tests/test_logic_adapter_integration.py
This change is being made to simplify logic adapters and to remove redundant data since the confidence score is now being stored on the statement object.
Closes #566
=> Change logic adapters to just return one value

chatterbot/chatterbot.py, chatterbot/conversation/session.py, examples/learning_feedback_example.py, tests/test_chatbot.py
This change is being made to cut down on the amount of code that depends on the default session existing. The goal is to _eventually_ remove this attribute and to create the session _when_ it is needed, instead of during initialization.
=> Require session id for generate_response method

chatterbot/ext/django_chatterbot/views.py, tests_django/test_api.py
This removes section of code in the API view that was incorrectly encoding dictionary data as a string.
Tests have been updated to make sure that this won't happen in the future.
Closes #602
=> Fix format of Django API view response data

chatterbot/ext/django_chatterbot/settings.py, chatterbot/storage/storage_adapter.py
Added boolean `use_django_models` option for ChatterBot settings to avoid problems with splitted databases usage.
=> fixed split databases usage for django

chatterbot/ext/django_chatterbot/settings.py, chatterbot/storage/django_storage.py, chatterbot/storage/storage_adapter.py, examples/django_app/example_app/settings.py
Currently the django_storage adapter tightly coupled with django_chatterbot. By introduce this fix, others can reuse storage adapter.
@gunthercox please provide your comments/suggestions on this PR.
=> Make use of django_storage

tests/base_case.py
This should increase the speed of the unit test process because it changes the check for if MongoDB is running from every time a test case is run, to only once per test case.
(The improvement is less than a second)
=> Only check if MongoDB is running once per test case

chatterbot/storage/sqlalchemy_storage.py, requirements.txt, tests/storage_adapter_tests/test_sqlalchemy_adapter.py
This makes a change so that a new sqlite database isn't created for
every test case. There are currently issues with disconnecting from
sessions in the beta version of the SQL adapter and these are
preventing the test database file from being able to be deleted
after the tests have completed.
=> Partially fix SQL adapter tests

chatterbot/storage/sqlalchemy_storage.py, chatterbot/storage/storage_adapter.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py
This change makes it possible to close the session and delete the test database file when unit tests have finished running.
A few other minor changes have been made as well (see commit messages).
***
For testing, I've made changes so that a single database file is created before the set of test cases are run and then it is deleted after. The database is cleared for each test case. These changes should make it more efficient to run the tests. Closes #707
=> Keep a reference to a single session in SQL alchemy adapter

chatterbot/chatterbot.py, chatterbot/comparisons.py, chatterbot/logic/logic_adapter.py, chatterbot/logic/multi_adapter.py, chatterbot/utils.py, tests/logic_adapter_tests/best_match_integration_tests/test_sentiment_comparison.py, tests/logic_adapter_tests/best_match_integration_tests/test_synset_distance.py, tests/test_comparisons.py
This corrects the issue where the ChatBot class always downloads NLTK assets even if it doesn't need them. Now, each statement comparison algorithm will be responsible for its own dependencies.
The design of this new setup maintains efficiency by ensuring that functions with the same name (they should do the same things) are only called once, even when multiple logic adapters use them.
=> Make callable classes for comparing statements

chatterbot/storage/sqlalchemy_storage.py, docs/sessions.rst, tests/base_case.py, tests/storage_adapter_tests/integration_tests/sqlalchemy_integration_tests.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py
=> Memory and file tests

chatterbot/storage/__init__.py, chatterbot/storage/sql_storage.py, tests/base_case.py, tests/storage_adapter_tests/integration_tests/sqlalchemy_integration_tests.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py
This changes the class name from `SQLAlchemyDatabaseAdapter` to `SQLStorageAdapter`. This change is because we abstract the inner workings of the SQL adapter. As a result the user never really needs to
know what library is being used internally.
=> Rename SQL Alchemy Database Adapter

chatterbot/storage/sql_storage.py
This pull request fixes a logging statement in the SQL adapter that was triggering errors. I've replaced it with an `exception` logging statement that has some useful functionality (It records the exception when the method is called within the scope of an `except` block.
> Logger.exception(msg, *args, **kwargs)
>
> Logs a message with level ERROR on this logger. The arguments are interpreted as for debug(). Exception info is added to the logging message. This method should only be called from an exception handler.
>
> ~ https://docs.python.org/3/library/logging.html#logging.Logger.exception
=> Fix logging statement in sql adapter

chatterbot/chatterbot.py, tests/base_case.py, tests/test_initialization.py
This pull request reveals what tests fail after setting the SQL storage adapter as the default for ChatterBot. These failures will need to be corrected before the adapter can be used in production.
**Updates:**
- After merging in #800 there are only a few errors remaining.
- After commit 49900b9c0933c2ef876d96fd426ff5b7600f5fb9 an additional dictionary casting error was removed.
***
```
======================================================================
FAIL: Test that an additional data attribute can be added to the statement
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/gcox/GitHub/ChatterBot/tests/logic_adapter_tests/test_data_cache.py", line 46, in test_additional_attributes_saved
self.assertIn('pos_tags', …
```
=> Switch to SQL adapter as default database adapter for ChatterBot

chatterbot/__main__.py
**Usage:**
```bash
python -m chatterbot list_nltk_data
```
**Output:**
Lists all NLTK data directories that contain files.
For #802 and the many related issues where problems with downloading the data happen. Adding this command will hopefully help find the NLTK data to delete is so that it will be re-downloaded.
=> Add command line utility to list NLTK data directories

chatterbot/__main__.py, docs/chatterbot.rst, docs/storage/index.rst, examples/default_response_example.py, examples/learning_feedback_example.py, examples/mailgun.py, examples/specific_response_example.py, examples/terminal_example.py, examples/tkinter_gui.py, tests/benchmarks.py
This PR will address 
***
Import version from command line https://github.com/gunthercox/ChatterBot/issues/795
Documentation updation about default ``SQLStorageAdapter`` storage adapter 
Replaced ``JsonStorageAdapter`` to ``SQLStorageAdapter`` in all examples
=> Docs and Example updation about SQLStorageAdapter 

chatterbot/trainers.py
This makes the following changes to the code in the training module:
- Variables have been renamed to be more accurate and descriptive.
- The ChatterBotCorpus trainer is no longer dependent on the ListTrainer.
- The entire statement history for a conversation is no longer stored (only the last statement is ever needed).
=> Clean up training code

docs/corpus.rst
=> Document the format of the ChatterBot corpus

tests/base_case.py
Since this text case properly handles creating and dropping the statement collections it is no longer required to assign random database names at test startup. Its probably a good idea not to do this anyway.
=> Use the same database for all tests when testing MongoDB

docs/training.rst
This adds a warning message in the documentation due to the performance issues when training with the Ubuntu dialog corpus.
CC @peterel
=> Add warning about Ubuntu dialog corpus

chatterbot/storage/sql_storage.py, requirements.txt, tests/training_tests/test_list_training.py
This issue was occurring because a new response was *trying* to be created in the database each time a statement with responses was updated. This operation fails if that response already exists.
Closes #831
Closes #842
Closes #844
=> Correct integrity error by checking for existing responses

chatterbot/ext/sqlalchemy_app/models.py, chatterbot/storage/sql_storage.py, setup.py
This adds a base class with an `id` attribute that each of the SQL alchemy models can inherit from.
=> Add a base class for SQL Alchemy models

chatterbot/storage/sql_storage.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py
=> Fix database name being ignored

chatterbot/trainers.py
This is a change allows `jsondb` to be removed as a dependency entirely once the `JsonFileStorageAdapter` is fully removed.
=> Remove direct dependency on jsondb for training file exports

chatterbot/storage/sql_storage.py, tests/base_case.py
Closes #868
This changes the default database type to be a sqlite file while still allowing an in-memory database to be used for testing. This change is needed so that a file will be created to store learned data when a chat bot is created using the default configuration.
=> Change SQL storage default to sqlite file instead of in-memory database

chatterbot/storage/sql_storage.py
This prevents the issues seen in #867. Query support (using ChatterBot's query builder) still needs to be added for this adapter.
Closes #867
=> Set query support to false in SQL storage adapter

chatterbot/input/hipchat.py, chatterbot/output/hipchat.py
Allow specification of ssl verification for hipchat adapters by adding an optional config variable to the chatbot instance.
=> Allow specification of ssl verification for hipchat adapters.

chatterbot/storage/sql_storage.py
This PR will enable sql engine with ``convert_unicode=True`` More information available here http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine.params.convert_unicode
Closes: https://github.com/gunthercox/ChatterBot/issues/887
=> convert_unicode on the String type

docs/django/wsgi.rst, docs/faq.rst
This adds general documentation on how to deploy a chat bot as a web application. It might be much too general at the moment so any feedback on how it could be improved would be greatly appreciated.
Closes #884
=> Add web deployment section to FAQ

chatterbot/trainers.py
closes: https://github.com/gunthercox/ChatterBot/issues/912
***
json.dump()
Serialize obj as a JSON formatted stream to fp (a .write()-supporting file-like object
If ensure_ascii is False, some chunks written to fp may be unicode instances
json.dumps()
Serialize obj to a JSON formatted str
If ensure_ascii is False, the result may contain non-ASCII characters and the return value may be a unicode instance
=> dump instead dumps

chatterbot/chatterbot.py, chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/storage/storage_adapter.py, examples/learning_feedback_example.py, examples/learning_new_response.py, requirements.txt, tests/test_context.py
This commit is in response to #873.  It allows sqlite pragma settings to be set.  This commit sets 
PRAGMA journal_mode=WAL
PRAGMA synchronous=NORMAL
when sqlite is used for the database.  These settings should speed things up while still maintaining data integrity.
See #873 for more details.
=> add sqlite pragma settings to sql_storage.py - change distinct to aggregate in mongodb.py

chatterbot/storage/sql_storage.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py
This updates the SQL storage adapter so that it won't automatically append ".db" to the end of the database name.
Closes #914
=> Don't append .db to sql database name

docs/django/index.rst, docs/faq.rst
This pull request makes changes to the documentation to address the following:
There have been a number of issues opened in the past regarding this. Typically there is a bit of confusion between ChatterBots storage adapters and Django's storage backends. Hopefully a bit of formal documentation on the subject will help explain this when it comes up again in the future.
This has come up a number of times as well. I've done my best to add an overview of this without getting grossly technical. I'm sure there are topics and concepts I could have gone much deeper into but this summarizes the gist of it.
=> A handful of documentation updates

chatterbot/adapters.py, chatterbot/logic/logic_adapter.py, docs/chatterbot.rst
=> Add more default value documentation

chatterbot/ext/django_chatterbot/settings.py, chatterbot/storage/django_storage.py, chatterbot/storage/jsonfile.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/storage/storage_adapter.py, docs/django/settings.rst, tox.ini
=> Allow any database model to be used

chatterbot/logic/mathematical_evaluation.py, requirements.txt, tests/logic_adapter_tests/test_mathematical_evaluation.py, tests_django/integration_tests/test_logic_adapter_integration.py
This pull request switches ChatterBot's mathematical evaluation logic adapter to use the Mathparse library (https://github.com/gunthercox/mathparse/)
Mathparse is a new library that is designed to efficiently handle the process of evaluating natural mathematical language.
***
Related to #1016
=> Use improved mathparse library for math evaluation logic adapter

chatterbot/ext/django_chatterbot/abstract_models.py
From Django 2.0 Release [note](https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0)...
> The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations. Consider squashing migrations so that you have less of them to update.
So on_delete must needed in ForeignKey so update to Django 2.0 won't break the development.
=> Support for Django 2.0

chatterbot/conversation/statement.py, chatterbot/ext/django_chatterbot/abstract_models.py, chatterbot/ext/sqlalchemy_app/models.py, chatterbot/storage/django_storage.py, chatterbot/storage/sql_storage.py, chatterbot/trainers.py, tests/training_tests/test_chatterbot_corpus_training.py, tests_django/integration_tests/test_chatterbot_corpus_training.py
=> Add tagging when training with SQL storage

docs/examples.rst, docs/quickstart.rst, docs/releases.rst, docs/tutorial.rst, docs/upgrading.rst
This adds a few links to connect pages in ways that might be helpful. Instructions to install ChatterBot have been added to the tutorial and quick start guide.
=> Documentation updates

chatterbot/conversation/statement.py, chatterbot/ext/sqlalchemy_app/models.py, chatterbot/ext/sqlalchemy_app/types.py, chatterbot/input/input_adapter.py, tests/training_tests/test_list_training.py
=> Fix sqlite 8-bit bytestrings with unicode coercion

.travis.yml, examples/django_app/requirements.txt, tox.ini
This pull request makes a few changes to update test requirement versions (such as Django 1.11 and Python 3.6) and also trims off some versions that _probably_ don't need to be tested against (such as Django 1.10).
=> Update python and requirement test versions

chatterbot/comparisons.py
When python-Levenshtein library is not pre-installed, the following logic in best_match is pretty slow:
```
for statement in statement_list:
confidence = self.compare_statements(input_statement, statement)
if confidence > closest_match.confidence:
statement.confidence = confidence
closest_match = statement
```
The problem is similar as [https://github.com/gunthercox/ChatterBot/issues/679](https://github.com/gunthercox/ChatterBot/issues/679).
try... except... block to check whether use difflib or python-Levenshtein has performance issue in iteration loop if it always enter except block. see: [http://paltman.com/try-except-performance-in-python-a-simple-test/](http://paltman.com/try-except-performance-in-python-a-simple-test/)
Move the try... except... block out of function scope.
=> Fixed performance issue of Levenshtein distance comparison when python-Levenshtein is not pre-installed

chatterbot/utils.py, tests_django/test_settings.py
This corrects an issue specific to the expanded notation that can be used to pass additional parameters to logic adapters.
Closes #1092
Closes #1012 
Closes #1157
=> Fix logic adapter kwargs

chatterbot/logic/best_match.py, chatterbot/logic/low_confidence.py, tests/logic_adapter_tests/test_low_confidence_adapter.py, tests_django/integration_tests/test_logic_adapter_integration.py
=> Allow a list of options to be passed to the low confidence adapter

chatterbot/trainers.py, runtests.py, setup.cfg, tests/base_case.py, tests/filter_integration_tests/test_filters_with_mongo_storage.py, tests/logic_adapter_tests/best_match_integration_tests/test_sentiment_comparison.py, tests/logic_adapter_tests/test_data_cache.py, tests_django/integration_tests/test_chatterbot_corpus_training.py, tests_django/test_settings.py
=> Don't display training progress bars while tests are running

chatterbot/storage/sql_storage.py
Using SQL Alchemy's queries directly will hopefully be more readable as well.
=> Remove untested __statement_filter method

chatterbot/ext/sqlalchemy_app/models.py
1. pip3 install --upgrade pymysql
2. database_uri="mysql+pymysql://root:root@localhost/test?charset=utf8mb4"
work well for me!
=> support for mysql with sqlalchemy

chatterbot/storage/django_storage.py
When using a logic adapter, if an unknown statement was given in Django project,  `chatterbot.ext.django_chatterbot.models.DoesNotExist: Statement matching query does not exist.` error used to pop up.  Happens in `chatterbot.logic.LowConfidenceAdapter` for default response and the other logic adapters as well.
=> Fix "Statement matching query does not exist" error

chatterbot/parsing.py, tests/test_parsing.py
@coolrb The script assumes 24hr format by default, to work for you scenario you have to write like this
Scenario 1
```Python
from chatterbot import parsing
text= u'Your dental appointment with Dr P. Delvour is scheduled for October 29, 4:00pm. ABC Dentist, 555-555-555.'
dates_ch = parsing.datetime_parsing(text)
print(dates_ch)
```
Update regular expression
```
re_time = r'(?P<hour>\d{1,2})(\:(?P<minute>\d{1,2})\s?(?P<convention>am|pm))'
```
Scenario 2:
```Python
from chatterbot import parsing
text= u'Your dental appointment with Dr P. Delvour is scheduled for October 29, 16:00. ABC Dentist, 555-555-555.'
dates_ch = parsing.datetime_parsing(text)
print(dates_ch)
```
Scenario 3:
Skip minutes, the regex will work.
```Python
from chatterbot import parsing
text= u'Your dental appointment with …
```
=> Datetime parsing does recognize am or pm

chatterbot/chatterbot.py
This makes a change so that developers can override the built in set of system logic adapters that ChatterBot uses.
This isn't something that is needed for typical use of ChatterBot but in some advanced cases it can be useful to disable them.
**Example usage**
```python
chatbot = ChatBot(
system_logic_adapters=[]
)
```
For #1273
=> Make it simpler to override system logic adapters.

dev-requirements.txt, setup.py, tests/input_adapter_tests/test_gitter_input_adapter.py, tests/input_adapter_tests/test_microsoft_input_adapter.py, tests/logic_adapter_tests/best_match_integration_tests/test_levenshtein_distance.py, tests/logic_adapter_tests/best_match_integration_tests/test_synset_distance.py, tests/logic_adapter_tests/test_best_match.py, tests/logic_adapter_tests/test_low_confidence_adapter.py, tests/output_adapter_tests/test_gitter_output_adapter.py, tests/output_adapter_tests/test_microsoft_output_adapter.py, tests/training_tests/test_twitter_trainer.py, tests/training_tests/test_ubuntu_corpus_training.py
These dependencies are included in standard Python 3 installations and no longer need to be installed as a part of the list of dev-dependencies.
=> Remove modules included in Python 3 from dev-requirements.txt

chatterbot/ext/django_chatterbot/abstract_models.py, chatterbot/ext/django_chatterbot/admin.py, chatterbot/ext/django_chatterbot/migrations/0012_statement_created_at.py
For #1391, include a record of the date and time that a statement is create at in the Django models. This also makes changes to the Django admin to allow filtering and displaying of the datetime.
=> Add a created_at time to the Django statement model

tests_django/test_settings.py
I noticed that `print` statements weren't logging output when running tests for Django. This could make debugging difficult.
=> Log Django test output to stdout

tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py
The order_by parameter was never implemented for the SQL storage adapter. This pull request adds tests with expected failures that should start passing after `order_by` is supported.
=> Add expected test failures for SQL Storage ordering

chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py, tests_django/test_django_adapter.py
This is an explicit `create` function for cases when the "update or create" functionality of the `update` method results in unwanted or unclear functionality.
=> Add create method to storage adapters

chatterbot/chatterbot.py, chatterbot/conversation.py, chatterbot/ext/django_chatterbot/abstract_models.py, chatterbot/ext/django_chatterbot/migrations/0014_remove_statement_extra_data.py, chatterbot/ext/sqlalchemy_app/models.py, chatterbot/input/hipchat.py, chatterbot/output/hipchat.py, chatterbot/storage/django_storage.py, chatterbot/storage/sql_storage.py, chatterbot/trainers.py, examples/django_app/tests/test_api.py, examples/django_app/tests/test_example.py, tests/logic_adapter_tests/test_data_cache.py, tests/test_chatbot.py, tests_django/integration_tests/test_statement_integration.py
The `tags` attribute provides a versatile yet defined structure and will now fully replace the `extra_data` dictionary of anythingness that was previously used for storing arbitrary information related to a statement.
=> Replace the extra_data attribute with tags

chatterbot/ext/django_chatterbot/abstract_models.py, chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py, tests_django/test_django_adapter.py
This adds tests and makes changes accordingly to help prevent the creation and addition of duplicate tags to a statement.
=> Mitigate the addition of duplicate tags

chatterbot/chatterbot.py, chatterbot/input/gitter.py, chatterbot/input/hipchat.py, chatterbot/input/input_adapter.py, chatterbot/input/mailgun.py, chatterbot/input/microsoft.py, chatterbot/input/terminal.py, chatterbot/input/variable_input_type_adapter.py, docs/conf.py, examples/django_app/example_app/views.py, tests/filter_integration_tests/test_filters_with_mongo_storage.py, tests/input_adapter_tests/test_gitter_input_adapter.py, tests/input_adapter_tests/test_input_adapter.py, tests/input_adapter_tests/test_microsoft_input_adapter.py, tests/input_adapter_tests/test_variable_input_type_adapter.py, tests_django/integration_tests/test_input_adapter_integration.py
The `conversation` is available on the statement object that gets passed in.
=> Remove conversation parameter from get_response and process_input methods

examples/tests/readme.md, tests/test_examples.py, tox.ini
This change results in fewer commands being required to run all the tests.
=> Move tests for examples into the tests directory

chatterbot/corpus.py, chatterbot/trainers.py, requirements.txt, tests/test_corpus.py
Closes #1416 (by adding the required tests)
For #1256 (decreases time consumption of corpus trainer)
=> Reduce the time complexity of ChatterBot corpus trainer

chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/storage/storage_adapter.py, chatterbot/trainers.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sql_adapter.py, tests/storage_adapter_tests/test_storage_adapter.py, tests_django/test_django_adapter.py
This adds bulk-creation capabilities to storage adapters to decrease the amount of time that training requires.
* Closes #1419
* Related to #1256
=> Add bulk-creation methods to storage adapters

chatterbot/logic/best_match.py, chatterbot/logic/logic_adapter.py, chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/trainers.py, chatterbot/utils.py, tests/logic_adapter_tests/test_best_match.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sql_adapter.py, tests/test_benchmarks.py, tests_django/test_django_adapter.py
This resolves a major performance issue where ChatterBot loads large numbers of statements into memory for processing as a part of the search process. Memory allocation at that size has a massive amount of overhead. With this change, a more reasonable amount of statements will be analysed at a time and the processing will not be continued if an optimal response (within a specified range of similarity) is found.
* Closes #1363 
* Closes #1206
* Closes #1140
* Closes #1138
* Closes #697
* Closes #679
* Closes #1139
This should also help with #1218 but doesn't resolve it completely. Tests I've conduced locally still demonstrate ~15 second response times for 50 MB of training data. This means that response times are still not optimal after training the bot with a dataset the size if the …
=> Make get_response_statements methods into lazy-loading generators

chatterbot/storage/sql_storage.py, tests/storage_adapter_tests/test_sql_adapter.py
This corrects a few outdated docstrings, does a small bit of code cleanup and removes tests and functionality for the read_only parameter since that is no longer a function on the other two storage adapters.
=> Clean up SQL Storage adapter

chatterbot/chatterbot.py, chatterbot/preprocessors.py, chatterbot/trainers.py, docs/preprocessors.rst, tests/test_preprocessors.py
This change is because the chatbot parameter is unused and removing it allows these methods to be passed in as parameters to a multiprocessing map function (related to #1470).
=> Remove chatbot parameter from preprocessors

chatterbot/ext/django_chatterbot/abstract_models.py, chatterbot/ext/django_chatterbot/migrations/0017_name_primary_key.py, chatterbot/ext/sqlalchemy_app/models.py, chatterbot/storage/sql_storage.py
* This prevents duplicate tags and allows more efficient operations to be performed to retrieve tags.
=> Use tag name as primary key

chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/trainers.py, tests/storage/test_mongo_adapter.py, tests/storage/test_sql_adapter.py, tests_django/test_django_adapter.py
Objects have a better ability to be optimized for better memory and processing usage than dictionaries do.
A revision for #1449
=> Modify create_many to use objects instead of dictionaries

chatterbot/stemming.py, chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/trainers.py, tests/test_stemming.py, tests/training/test_chatterbot_corpus_training.py, tests/training/test_twitter_trainer.py, tests/training/test_ubuntu_corpus_training.py
This change will reduce the size of the result matching set by decreasing the number of possible matches based on the need for similar text to have at least two neighboring matches.
For #1452
=> Switch to bigram strategy for text indexing

chatterbot/logic/best_match.py, chatterbot/stemming.py, chatterbot/storage/mongodb.py, tests/test_filters.py, tests/test_stemming.py, tests/training/test_list_training.py, tests_django/test_logic_adapter_integration.py
Using the value of this field increases the possible number of matches that can be returned. For example, matches with only differing punctuation would now be returned.
Closes #310
=> Use search_in_response_to value for selecting response statements

chatterbot/stemming.py, tests/test_stemming.py
This revises the class added in #1462. The `stem` method is not needed because in all cases, only either the stemmed word list, or the bigram pair string are required.
=> Remove unused stem method from stemmer

.travis.yml, chatterbot/trainers.py
This makes is easier to hide training progress indicators during unit testing for the programs in the `examples/` directory.
=> Allow an environment variable to control is training progress is shown

chatterbot/chatterbot.py, chatterbot/stemming.py, tests/__init__.py, tests/base_case.py
NLTK corpus check logs were being printed numerous times in test output. This change allows the initialization process for the stemmer to be easily controlled so that it can be run once.
=> Modify stemmer to only download stopwords once

chatterbot/chatterbot.py, chatterbot/logic/best_match.py, chatterbot/response_selection.py, chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, tests/logic/test_data_cache.py, tests/storage/test_sql_adapter.py, tests/test_chatbot.py, tests/training/test_chatterbot_corpus_training.py, tests/training/test_list_training.py, tests/training/test_twitter_trainer.py, tests/training/test_ubuntu_corpus_training.py, tests_django/test_chatterbot_corpus_training.py, tests_django/test_django_adapter.py
This will provide a benefit when working with large queries by allowing the search process to be terminated sooner.
For #613
=> Switch filter method to a generator with page_size parameter

chatterbot/logic/best_match.py, chatterbot/logic/logic_adapter.py, tests/logic/test_best_match.py
=> Allow statements containing specific words to be excluded from response results

chatterbot/logic/best_match.py, chatterbot/stemming.py, chatterbot/storage/storage_adapter.py, chatterbot/trainers.py, tests/logic/best_match_integration_tests/test_levenshtein_distance.py, tests/test_chatbot.py, tests/test_stemming.py, tests/training/test_chatterbot_corpus_training.py, tests/training/test_list_training.py, tests/training/test_twitter_trainer.py, tests/training/test_ubuntu_corpus_training.py
Using the stemmed statement text should provide more efficient search and text comparison functionality.
=> Use stemmed text to search for statement matches

chatterbot/comparisons.py, chatterbot/languages.py, chatterbot/storage/storage_adapter.py, chatterbot/tagging.py, chatterbot/trainers.py, chatterbot/utils.py, docs/utils.rst, tests/test_comparisons.py, tests/test_languages.py, tests/test_utils.py
This will allow a single language attribute to be shared among different methods that need either 'english' or 'eng' as parameters.
```python
def generate_language_classes():
"""
pip install beautifulsoup4==4.6
"""
import requests
from bs4 import BeautifulSoup
DOWNLOAD_URL = 'https://www.loc.gov/standards/iso639-2/php/code_list.php'
SKIP_IF_LANGUAGE_NAME_CONTAINS = (
'Old',
'Ancient',
'Low',
'Middle',
'High',
'00',
'ca.',
'languages',
'Languages',
'Reserved',
'Not applicable',
)
BIBLIOGRAPHIC_INDICATOR = ' (B)'
response = requests.get(DOWNLOAD_URL)
soup = BeautifulSoup(response.content, 'lxml')
table = soup.find('table', attrs={
'border': '1'
})
extracted_data = {}
for row in table.find_all('tr'):
columns = [td.text for td in row.find_all('td')]
if not columns:
continue
iso_code = …
```
=> Add languages with iso-639 attributes

examples/django_app/example_app/templates/nav.html
Replaced `line 21` of "examples/django_app/example_app/templates/nav.html" i.e., 
`<a class="nav-link" href="{% url 'chatterbot:chatterbot' %}">API</a>` with 
`<a class="nav-link" href="{% url 'chatterbot' %}">API</a>`.
This resolved the issue 
> 'chatterbot' is not a registered namespace
=> modified line-21 in examples/django_app/example_app/templates/nav.html

chatterbot/constants.py, chatterbot/ext/django_chatterbot/migrations/0018_text_max_length.py
Most databases have a maximum allowed length of 255 characters for char fields.
Closes #1546
=> Change maximum allowed text length

chatterbot/chatterbot.py, chatterbot/logic/best_match.py, chatterbot/logic/logic_adapter.py, chatterbot/logic/mathematical_evaluation.py, chatterbot/logic/specific_response.py, chatterbot/logic/time_adapter.py, chatterbot/logic/unit_conversion.py, chatterbot/search.py, examples/tagged_dataset_example.py, tests/logic/test_data_cache.py, tests/test_chatbot.py, tests/test_search.py
This allows an additional parameter to be passed in to control what statements get selected when generating the list of possible responses.
* For #1542 item 2
* For #1232
* Closes #1179
* Closes #1541
* Resolves #1536
=> Allow parameter to be passed in for response filter

chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/storage/storage_adapter.py, docs/logic/create-a-logic-adapter.rst, tests/base_case.py, tests/test_parsing.py, tests/training/test_database_export.py, tests/training/test_ubuntu_corpus_training.py, tests_django/test_chatbot.py
This simplifies the `get_model` method on storage adapters.
I have also included some code cleanup related to the `super` calls in various classes (I like how clean the Python 3 version of this looks). There are also Django tests added, this was by accident, but they pass and increase the overall resilience of the test suite so I'm deciding to leave them.
I apologize for the broad scope of this pull request.
=> Simplify storage adapter model get method

chatterbot/chatterbot.py, chatterbot/conversation.py, chatterbot/logic/specific_response.py, tests/storage/test_mongo_adapter.py, tests/storage/test_sql_adapter.py, tests/test_conversations.py, tests/test_response_selection.py, tests/test_search.py
The original Statement object had a __hash__ function defined which was yielding different results when other Statement object types were used. This removes the hash method and makes a change to how similar statements are counted.
Possibly related to #1375
=> Change where / how hashing is done for statements

setup.py
ChatterBot doesn't support Python version less than 3.
This warning will hopefully help eliminate any confusion related to this.
=> Stop installation on Python < 3

chatterbot/comparisons.py, chatterbot/tagging.py, chatterbot/tokenizers.py, tests/test_chatbot.py
This makes better use of the chatterbot-corpus module to train the `PunktSentenceTokenizer`.
In addition, this allows more languages to be supported for splitting sentences.
=> Use chatterbot-corpus to train PunktSentenceTokenizer

requirements.txt
Fixes #1664. Not sure if `pytz` had to be pinned, if so don't hesitate to point at which version should be used. :+1:
=> Add pytz to requirements.txt

chatterbot/languages.py, tests/test_languages.py
The incorrect number of classes was being returned.
This also adds a convenience function to return the classes.
=> Fix tests for getting language classes

.gitignore, MANIFEST.in, chatterbot/__init__.py, chatterbot/__main__.py, docs/conf.py, setup.cfg, setup.py, tests/test_cli.py
This is a workaround for import errors that occur when installing directly from GitHub via pip.
For example:
```
pip install git+git://github.com/gunthercox/chatterbot@master#egg=chatterbot
```
=> Read version from config instead of using import

docs/logic/create-a-logic-adapter.rst
I noticed the indentation in one of the examples was off creating some confusion for me at first.
=> Fix indentation in docs

dev-requirements.txt, docs/storage/index.rst, requirements.txt
Pymongo isn't required unless the Mongo DB storage adapter is being used. By not installing pymongo automatically, the installation footprint of ChatterBot is decreased in size, which can be useful when installing on devices that have limited storage space.
=> Remove pymongo from main dependency list

chatterbot/parsing.py
This Pull Request is to address this [issues](https://github.com/gunthercox/ChatterBot/issues/1347).
First, In this code
https://github.com/gunthercox/ChatterBot/blob/c429fa50c5edf9198030880b9d9151de73a6dced/chatterbot/parsing.py#L648
`today` return datetime instance include time, not only date.
So I solved this problem by setting the time element to zero.
Second, In this code
https://github.com/gunthercox/ChatterBot/blob/c429fa50c5edf9198030880b9d9151de73a6dced/chatterbot/parsing.py#L31
If the string is matched to `(\sam|pm)?`, am or pm is not assigned for the `convention` group.
So I solved this problem by modifying this regex.
And as a result, if you run this code,
```python
from chatterbot import parsing
print(parsing.datetime_parsing(u"Your dental appointment with Dr P. Delvour is …
```
=> Fixed issue that do not correctly recognize am and pm in re_time.

chatterbot/trainers.py
This makes possible utf8 chat bot's database to be exported.
=> Fix export_for_training to encode utf8

chatterbot/storage/mongodb.py
This Pull Request is addressed to: [this issue](https://github.com/gunthercox/ChatterBot/issues/1730)
When using MongoDB as StorageAdapter, special characters from input messages are triggering regex patterns which is crashing the application.
=> Fix regular expression in filter

chatterbot/logic/specific_response.py, chatterbot/trainers.py
This pull request is intended to solve [this issue](https://github.com/gunthercox/ChatterBot/issues/1677).
It appears that you are trying to compare the member variable `text` and `self.input_text` of statement.
However, this does not call the `__str__` function, it simply compares the id of two objects and will always return false.
Therefore, I call the `str` function to explicitly call the `__str__` function.
I tested this branch using this [test code](https://github.com/gunthercox/ChatterBot/blob/master/examples/specific_response_example.py).
Before, Chatterbot returns invaild answer.
After revision, Chatterbot return vaild answer.
=> make can_process function use __str__ of Statement class

chatterbot/corpus.py
While this can be patched by installing chatterbot_corpus I feel we should just define the variable here, and prevent people in the future from opening issues regarding the same.
Issues this patches: #1894 , #1852, #1757, #1727, #1689,  #1708, #833
Also chatterbot_corpus is not installed by pip, for some reason
=> Patch ModuleNotFoundError (No module named 'chatterbot_corpus')

chatterbot/comparisons.py, chatterbot/corpus.py, chatterbot/exceptions.py, chatterbot/logic/time_adapter.py, chatterbot/logic/unit_conversion.py, dev-requirements.txt, requirements.txt
Right now the issue tracker is prolific with tickets that have titles similar to "Help, I had an error while installing ChatterBot". The intention of this pull request is to make changes that eliminate a number of dependencies that could be considered optional from the primary installation process. Although I think `spacy` and `chatterbot_corpus` are the primary culprits; `spacy` requiring build dependencies to compile, and `chatterbot_coupus` currently installing via a GitHub url... I think the the idea of having dependencies required in order to enable features might be an advantage in general to reduce the footprint and efficiency of the overall ChatterBot installation.
=> Don't install several dependencies by default

docs/logic/create-a-logic-adapter.rst
If `.process()` in your custom Logic Adapter returns a tuple with `(confidence, return_statement)`, like currently described in the docs, then running the bot gives an error:
```
AttributeError: 'tuple' object has no attribute 'text' chatterbot
```
This was addressed also in https://github.com/gunthercox/ChatterBot/issues/1208 and it's probably worth to update the docs to reflect that `.confidence` is an attribute on a `Statement()`.
=> Fix error in return variable documentation

chatterbot/chatterbot.py, chatterbot/comparisons.py, chatterbot/components.py, chatterbot/languages.py, chatterbot/logic/logic_adapter.py, chatterbot/preprocessors.py, chatterbot/search.py, chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/tagging.py, chatterbot/trainers.py, chatterbot/utils.py, pyproject.toml, tests/storage/test_mongo_adapter.py, tests/storage/test_sql_adapter.py, tests/test_benchmarks.py, tests/test_preprocessors.py, tests/test_tagging.py, tests/training/test_ubuntu_corpus_training.py
Spacy supports functionality to improve performance when processing large amounts of text. Example from their documentation:
```diff
texts = ["This is a text", "These are lots of texts", "..."]
- docs = [nlp(text) for text in texts]
+ docs = list(nlp.pipe(texts))
```
https://spacy.io/usage/processing-pipelines#processing
***
It also looks like there are `enable` and `disable` options that can be used to include or exclude parts of the text processing pipeline. These might be a possible place to look for future performance improvements, but right now it isn't clear if adjusting these makes a significant impact.
***
Closes #2350
=> Use bulk processing from spacy pipeline

chatterbot/chatterbot.py, chatterbot/comparisons.py, chatterbot/logic/time_adapter.py, chatterbot/tagging.py, docs/setup.rst, examples/terminal_example.py, pyproject.toml, tests/test_chatbot.py
Overall the `PhraseMatcher` seems to be better suited for the purpose of this logic adapter (matching a set of examples of questions asking what the current time is). Notably this change was brought about by noticing that the `TimeLogicAdapter` was being overly confident in its identification of time related statements and was yielding a high number of false-positives.
***
Additionally I'm going to use this pull request to close off a number of old issues related to `nltk` since this logic adapter was the last place `nltk` was used in ChatterBot.
Closes #1746, closes #2138, closes #1953, closes #1857, closes #1856, closes #1813, closes #1800, closes #1720, closes #1618, closes #1678
=> Modify TimeLogicAdapter to use SpaCy PhraseMatcher instead of NLTK NaiveBayesClassifier

chatterbot/chatterbot.py, tests/test_chatbot.py
This pull request makes it so that tags will be persisted to the statement the bot generates.
For example:
```python
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
bot = ChatBot('Debug')
trainer = ChatterBotCorpusTrainer(bot, read_only=True)
trainer.train('chatterbot.corpus.english')
bot_input = bot.get_response('Hello')
print(bot_input.tags, bot_input.get_tags())
```
Closes #2219
I believe this also closes #2068, and closes #1626
=> Persist tags to output

chatterbot/tagging.py, chatterbot/trainers.py, docs/training.rst, tests/training/test_data/json_corpus/1.json
This adds a fix so that when training using files (ex. `json`) that specify an `in_response_to` field the key will be used instead of the sequential file order.
* For #2411
***
Also includes a few documentation updates to help better convey the expected structure of `json` files.
* Closes #2409
=> Generate response search index when in_response_to key is present in files
