.travis.yml, chatterbot/adapters/storage/__init__.py, chatterbot/adapters/storage/mongodb.py, chatterbot/chatterbot.py, examples/terminal_mongo_example.py, requirements.txt, tests/storage_adapter_tests/test_mongo_adapter.py
This adds support for connecting ChatterBot to MongoDB for storing its learned conversation data.
Closes #42
=> Created MongoDB adapter

chatterbot/adapters/storage/mongodb.py
values = list(statement)[0]
IndexError: list index out of range
=> no need to multiply by 'count'

.travis.yml, chatterbot/adapters/logic/__init__.py, chatterbot/adapters/logic/closest_match.py, chatterbot/adapters/logic/closest_meaning.py, tests/logic_adapter_tests/test_closest_meaning.py
I've started looking into using [NLTK](http://www.nltk.org/) to compare two statements by the meaning of their content.
**Closest Match**
=> Add closest-match logic adapter

requirements.txt
Compatible allows automatic security updating without fear of breakage.
=> Changed requirement for requests to compatible

chatterbot/corpus/data/english/trivia.json, tests/corpus_tests/test_corpus.py
This is just an additional training corpus that has a few random facts.
=> Added trivia corpus

.gitignore, chatterbot/adapters/exceptions.py, chatterbot/adapters/logic/closest_match.py, chatterbot/adapters/logic/closest_meaning.py, chatterbot/adapters/storage/jsondatabase.py, chatterbot/chatterbot.py, tests/base_case.py, tests/integration_tests.py, tests/logic_adapter_tests/test_closest_match.py, tests/logic_adapter_tests/test_closest_meaning.py, tests/storage_adapter_tests/test_jsondb_adapter.py, tests/test_chatbot.py, tests/training_tests/test_training.py, tests/training_tests/test_training_from_corpus.py
1. This cleans up and organizes a few of the test cases.
2. There is also an issue with randomly failing test cases as a result of the values being returned from `get_response` that I am aiming to correct once the cause of the issue is identified. It appears that these tests are only randomly failing under python 3 environments.
=> General code cleanup

examples/tkinter_gui.py
I created a simple GUI that users can run to interact with ChatterBot.
=> Add Tkinter example GUI

chatterbot/adapters/storage/jsondatabase.py, chatterbot/adapters/storage/mongodb.py, chatterbot/chatterbot.py, chatterbot/conversation/statement.py, chatterbot/training.py, tests/logic_adapter_tests/test_data_cache.py, tests/storage_adapter_tests/test_jsondb_adapter.py
This pull request has two parts:
Closes #66
=> Change response structure

chatterbot/adapters/storage/mongodb.py
Added kwarg for database_uri, which is in the standard MongoDB URI format.
This is a rewrite of PR #99 , where instead of a new adapter, the feature is just written into the new adapter.
=> Added remote mongodb capabilities to adapter.

chatterbot/adapters/adaptation.py, chatterbot/adapters/adapter.py, chatterbot/adapters/exceptions.py, chatterbot/adapters/logic/__init__.py, chatterbot/adapters/logic/closest_match.py, chatterbot/adapters/logic/closest_meaning.py, chatterbot/adapters/logic/logic.py, chatterbot/adapters/logic/mixins.py, chatterbot/adapters/logic/multi_adapter.py, chatterbot/adapters/storage/jsondatabase.py, chatterbot/adapters/storage/mongodb.py, chatterbot/adapters/storage/storage.py, chatterbot/chatterbot.py, tests/io_adapter_tests/test_json_adapter.py, tests/io_adapter_tests/test_no_output_adapter.py, tests/io_adapter_tests/test_terminal_adapter.py, tests/logic_adapter_tests/test_closest_match.py, tests/logic_adapter_tests/test_closest_meaning.py, tests/logic_adapter_tests/test_data_cache.py, tests/logic_adapter_tests/test_mixins.py, tests/storage_adapter_tests/test_jsondb_adapter.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/test_adaptation.py, tests/test_chatbot.py
=> Add support for multiple logic adapters

chatterbot/adapters/logic/closest_meaning.py, chatterbot/utils/pos_tagger.py, chatterbot/utils/stop_words.py, chatterbot/utils/word_net.py, tests/test_utils.py
This PR includes simple implementations of the NLTK functions used by the closest meaning adapter. The structure of the system makes it easy to improve each individual component very easily when we want to make the analysis more complex.
=> Add custom implementations for various NLTK functions

chatterbot/adapters/adaptation.py, chatterbot/adapters/io/__init__.py, chatterbot/adapters/io/multi_adapter.py, chatterbot/chatterbot.py, examples/terminal_example.py, tests/test_adaptation.py
This PR add support for using multiple io adapters.
At the moment, I am currently just getting input from the first io adapter. To allow multiple inputs, we may have to restructure a couple of things. I haven't thought too much about it yet though, so I'm not sure what will have to be changed.
=> Multiple io adapters

chatterbot/adapters/adapter.py, chatterbot/adapters/io/io_json.py, chatterbot/adapters/io/no_output.py, chatterbot/adapters/io/terminal.py, chatterbot/adapters/io/tts.py, chatterbot/adapters/logic/closest_match.py, chatterbot/adapters/logic/closest_meaning.py, chatterbot/adapters/logic/evaluate_mathematically.py, chatterbot/adapters/logic/mixins.py, chatterbot/adapters/logic/multi_adapter.py, chatterbot/adapters/logic/time_adapter.py, chatterbot/adapters/storage/jsondatabase.py, chatterbot/adapters/storage/mongodb.py, chatterbot/adapters/storage/twitter_storage.py, chatterbot/conversation/signature.py, chatterbot/utils/pos_tagger.py, chatterbot/utils/stop_words.py, chatterbot/utils/word_net.py
Most of the documentation is pretty simple, but the structure of ChatterBot is pretty straightforward.
=> Add basic class documentation

chatterbot/corpus/data/italian/conversations.json, chatterbot/corpus/data/italian/greetings.json, chatterbot/corpus/data/italian/trivia.json
=> Italian training data

chatterbot/adapters/output/__init__.py, chatterbot/adapters/output/mailgun.py, examples/mailgun.py, tests/output_adapter_tests/test_mailgun_adapter.py
I created a [mailgun](https://www.mailgun.com/) email adapter a while back but was unable to get it set up to retrieve mail from the account's inbox (I forget the reason but I will look back into it). For the time being, I have converted the completed part of the adapter into an OutputAdapter, pending the merge of #163.
=> Add mailgun output adapter

.travis.yml
:chart_with_upwards_trend: :eyes:
=> Added operating systems to travis builds

chatterbot/corpus/data/italian/conversations.json
Just added some basics italian conversations
=> Updated conversations.json in italian language

chatterbot/chatterbot.py, chatterbot/conversation/__init__.py, chatterbot/conversation/response.py, chatterbot/conversation/statement.py, chatterbot/training/trainers.py, tests/conversation_tests/test_statements.py, tests/storage_adapter_tests/test_jsondb_adapter.py
This was creating an issue during serialization because a serialized response object was expected.
Closes #203
=> Correct issue with statement response serialization

chatterbot/corpus/corpus.py, tests/corpus_tests/test_corpus.py
This is an issue that is appearing in Travis CI output, but I can't replicate the issue locally.
=> Correct failing Travis build for corpus data tests

chatterbot/adapters/adapter.py, chatterbot/adapters/logic/base_match.py, chatterbot/adapters/logic/closest_match.py, chatterbot/adapters/logic/closest_meaning.py, chatterbot/adapters/logic/mixins.py, chatterbot/chatterbot.py, examples/terminal_example.py, examples/terminal_mongo_example.py
=> Add info level logging

docs/adapters/storage.rst
=> twitter adapter documentation

tests/test_chatbot.py
=> Add unit testing for extra data in input statements

chatterbot/ext/django_chatterbot/models.py
Makes admin interface much more intuitive to work with.
=> add `__str__` method to models

chatterbot/adapters/storage/jsonfile.py, docs/adapters/storage.rst, tests/storage_adapter_tests/test_json_file_storage_adapter.py
=> Allow flag to be set to silence performance warning

chatterbot/adapters/storage/jsonfile.py, tests/storage_adapter_tests/test_json_file_storage_adapter.py
This method previously wasn't being tested.
=> Add test for json_to_object method

chatterbot/adapters/storage/django_storage.py, chatterbot/adapters/storage/jsonfile.py, chatterbot/adapters/storage/mongodb.py, chatterbot/adapters/storage/storage_adapter.py, chatterbot/adapters/storage/twitter_storage.py
=> Support queries in storage adapters by default

chatterbot/corpus/readme.fr.md
Hi there I would like to help, I'm french so count me in if you need so stuff ;) 
Take care.
=> Update some spelling :)

.travis.yml, chatterbot/ext/django_chatterbot/views.py, chatterbot/utils/queues.py, examples/django_app/example_app/settings.py, examples/django_app/example_app/templates/app.html, examples/django_app/tests/test_api.py, examples/django_app/tests/test_integration.py
=> Test that response history is maintained in Django API view

chatterbot/utils/parsing.py, tests/test_parsing.py
Let me know if i am going in the right direction
Todo
1. Documentation...
2. List of all supported date patterns
3. Add tests
=> Added date parsing module

tests/base_case.py, tests/storage_adapter_tests/integration_tests/json_integration_tests.py, tests/storage_adapter_tests/integration_tests/mongo_integration_tests.py, tests/test_adapter_validation.py
=> Clean up integration tests

chatterbot/adapters/input/__init__.py, chatterbot/adapters/input/gitter.py, chatterbot/adapters/output/__init__.py, chatterbot/adapters/output/gitter.py, examples/gitter_example.py
=> Add Gitter input and output adapters

chatterbot/adapters/output/gitter.py, chatterbot/adapters/output/hipchat.py, chatterbot/adapters/output/mailgun.py, chatterbot/adapters/output/output_adapter.py, chatterbot/adapters/output/output_format_adapter.py, chatterbot/adapters/output/terminal.py, chatterbot/chatterbot.py, tests/output_adapter_tests/test_output_adapter.py
This makes it possible for the output adapter to make a decision about if some kind of action (such as an API call) should be taken based on that confidence value.
=> Pass logic adapter confidence to the output adapter

chatterbot/chatterbot.py, tests/base_case.py, tests/test_chatbot.py
=> Allow chat bot to be created from json config file

chatterbot/adapters/storage/mongodb.py
false==True is unnecessary since it's a boolean, so you can write just "if false"
=> false==True is unnecessary

chatterbot/corpus/data/french/math_words.json
French math-words have been added.
=> french math_words

chatterbot/adapters/input/__init__.py, chatterbot/adapters/input/mailgun.py, docs/adapters/input.rst, examples/mailgun.py, tests/input_adapter_tests/test_mailgun.py
=> Add Mailgun input adapter

chatterbot/adapters/storage/mongodb.py
For #377, Clean up logic of Mongo DB adapter
For #238, I've added more verbose logging in the case of a bulk write error.
=> Attempt to resolve issue with response field not being updated in Mongo DB

chatterbot/adapters/logic/logic_adapter.py, tests/logic_adapter_tests/test_logic_adapter.py
=> Add check for if logic adapter string parameters need to be imported

.travis.yml
=> Enable testing on Django 1.10

chatterbot/chatterbot.py, chatterbot/ext/django_chatterbot/management/commands/train.py, chatterbot/trainers.py, docs/django/index.rst, docs/django/settings.rst, docs/django/training.rst, examples/django_app/example_app/settings.py, examples/django_app/tests/test_commands.py, setup.py
=> Add Django management command to train chat bot

chatterbot/adapters/storage/mongodb.py, tests/storage_adapter_tests/test_mongo_adapter.py
=> Handel the case that a Mongo DB statement does not have an in_response_to attribute

chatterbot/ext/django_chatterbot/views.py
=> Remove check for ajax request

chatterbot/chatterbot.py, chatterbot/conversation/comparisons.py, chatterbot/logic/time_adapter.py, requirements.txt, tests/logic_adapter_tests/test_sentiment.py
The goal of this pull request is to reduce the number of dependencies that ChatterBot has and to make it the existing codebase clearer to understand. Textblob is mostly just a wrapper around NLTK and by removing it, it becomes easier to control how data is analysed and used.
=> Remove dependency on Textblob

docs/logic/create-a-logic-adapter.rst
=> Add details about directory structure of custom logic adapter

.travis.yml, chatterbot/logic/__init__.py, tests/benchmarks.py
=> Add performance benchmarking script

chatterbot/parsing.py, tests/test_parsing.py
=> Linting and tests for datetime parsing

examples/learning_feedback_example.py
second param passed in  which was causing bot.learn_response which was causing the error.
Closes #465
=> In reference to issue 465

chatterbot/input/hipchat.py, chatterbot/output/hipchat.py
Add session management to input adapters, this fix will closes #474
=> hipchat session management

chatterbot/ext/django_chatterbot/models.py, tests_django/integration_tests/test_statement_integration.py
=> Give Django Statement & Response models the same attributes as ChatterBot Statements & Responses

chatterbot/input/variable_input_type_adapter.py, tests_django/integration_tests/test_input_adapter_integration.py, tests_django/integration_tests/test_output_adapter_integration.py
=> Make sure default Django input and output adapters work with the Statement & Response models

chatterbot/storage/jsonfile.py, requirements.txt, tests/base_case.py, tests/test_initialization.py
- Speeds up time tests take to run
- Simplifies test code so that a json file does not have to be created and removed for every test case
=> Run json database in-memory when testing

docs/django/wsgi.rst, examples/django_app/example_app/wsgi.py
=> wsgi should point example_app

chatterbot/comparisons.py, chatterbot/input/gitter.py, chatterbot/input/hipchat.py, chatterbot/input/microsoft.py, chatterbot/output/microsoft.py, chatterbot/parsing.py, chatterbot/response_selection.py, chatterbot/storage/django_storage.py, chatterbot/utils.py, setup.cfg, tests/base_case.py, tests/test_adapter_validation.py, tests/test_chatbot.py
=> Fix small code formatting issues

chatterbot/adapters.py, chatterbot/chatterbot.py, chatterbot/logic/multi_adapter.py, chatterbot/utils.py, tests/test_adapter_validation.py
=> Move adapter type exception to adapter class

readme.md
I have made a heroku live example for chatterbot to more familiar with chatterbot and what it does. you can access this app from here https://chatterbot-live-example.herokuapp.com/
Ref issue: https://github.com/gunthercox/ChatterBot/issues/493
=> chatterbot live example

readme.md
JimTheBot is a bot running on sgoblin's experimental Rhubarb Chat platform.
It has now been added to the examples section.
=> Added JimTheBot by sgoblin to examples

chatterbot/logic/logic_adapter.py
Corrects broken documentation link mentioned in https://github.com/gunthercox/ChatterBot/issues/532#issuecomment-269212362
Closes https://github.com/gunthercox/ChatterBot/issues/532
=> Update doc link

chatterbot/chatterbot.py, chatterbot/conversation/session.py, examples/django_app/tests/test_example.py, examples/learning_feedback_example.py, tests/test_chatbot.py, tests/test_context.py, tests/test_sessions.py, tests_django/test_integration.py
This removes the `get_default` and `update_default` methods.
Closes #527
=> Remove default session methods

docs/logic/index.rst
The place of response_selection_method and response_selection_method was wrong. They should be exchanged.
=> Setting parameters example code is wrong

docs/django/training.rst, docs/training.rst
Once #549 is merged, this closes #522
=> Document training path methods

chatterbot/ext/django_chatterbot/models.py, tests_django/integration_tests/test_statement_integration.py
=> Add missing serialize method to Response model

chatterbot/chatterbot.py, chatterbot/input/gitter.py, chatterbot/preprocessors.py, chatterbot/utils.py, docs/index.rst, docs/preprocessors.rst, docs/utils.rst, tests/test_preprocessors.py, tests/test_utils.py
This adds a new feature called _preprocessors_. These are simple functions that modify the input statement before it is processed by the logic adaper.
=> Convert clean_whitespace utility into a preprocessor

.travis.yml, chatterbot/chatterbot.py, chatterbot/conversation/statement.py, chatterbot/logic/multi_adapter.py, dev-requirements.txt, docs/conf.py, docs/django/index.rst, docs/django/training.rst, docs/encoding.rst, docs/input/index.rst, docs/logic/index.rst, docs/output/index.rst, docs/quickstart.rst, docs/tutorial.rst, test-requirements.txt
Docs have broken in the past in such a way that they wouldn't build when they get automatically pushed to __read the docs__. This helps make sure this doesn't happen.
=> Validate docs durring tests

chatterbot/trainers.py, tests/training_tests/test_twitter_trainer.py
=> Allow seed word to be set for Twitter training adapter

chatterbot/logic/mathematical_evaluation.py, requirements.txt, tests/logic_adapter_tests/test_mathematical_evaluation.py
This pull request updated tests to reflect issues found by @martmists (see #581).
The following changes have been made.
- Fix display formatting for exponents
- Split up tests that test more than one thing
- Remove dependence on numpy
=> Fix a few testing gaps for math evaluation

chatterbot/chatterbot.py, tests/test_chatbot.py
This value is already stored on the statement object.
=> Don't return confidence from generate_response method

chatterbot/corpus/data/indonesia/greetings.corpus.json
Update Greeting Corpus for Indonesia
=> Update Greeting Corpus for Indonesia

chatterbot/corpus/data/french/math_words.json
=> French Corpus Correction

docs/django/wsgi.rst
While reading the Django docs, I noticed a few spelling errors. I fixed them on this branch.
=> Fixed spelling errors.

chatterbot/conversation/statement.py, tests/test_comparisons.py
=> Fix non-string type values from breaking comparison algorithms

docs/conversations.rst, docs/django/index.rst, docs/django/views.rst, docs/filters/create_a_new_filter.rst, docs/index.rst, docs/input/create-an-input-adapter.rst, docs/input/index.rst, docs/logic/create-a-logic-adapter.rst, docs/logic/index.rst, docs/output/create-an-output-adapter.rst, docs/sessions.rst, docs/storage/create-a-storage-adapter.rst, docs/training.rst, docs/tutorial.rst
Fixed some minor typos in the doc files
=> correct various spelling mistakes in docs

docs/logic/create-a-logic-adapter.rst
Fixed a typo in the code snippet
=> Fixed a typo in the code snippet

readme.md
=> Fixed a typo in readme.md

docs/chatterbot.rst, docs/corpus.rst, docs/glossary.rst, docs/index.rst, docs/preprocessors.rst, docs/upgrading.rst
This makes a few small changes to improve the documentation.
=> Documentation updates

.travis.yml, chatterbot/chatterbot.py, chatterbot/comparisons.py, chatterbot/input/mailgun.py, chatterbot/input/variable_input_type_adapter.py, chatterbot/parsing.py, chatterbot/preprocessors.py, chatterbot/storage/sqlalchemy_storage.py, chatterbot/utils.py, examples/learning_feedback_example.py, examples/microsoft_bot.py, examples/terminal_example.py, examples/terminal_mongo_example.py, examples/tkinter_gui.py, examples/twitter_training_example.py, setup.cfg, tests_django/test_api.py
This helps ensure that code in the project conforms to the Python style guide.
=> Enable PEP8 checks in Travis CI

docs/contributing.rst, docs/developers.rst, docs/index.rst, docs/releases.rst
This adds documentation for contributing developers
=> Add documentation

chatterbot/ext/django_chatterbot/models.py
This will make it easier for other developers to extend these models if they wanted to add additional fields.
=> Create and use abstract base models for Django

docs/logic/index.rst
=> Fix some typos.

chatterbot/logic/multi_adapter.py, docs/logic/create-a-logic-adapter.rst, docs/logic/multi-logic-adapter.rst, docs/logic/response_selection.rst, docs/preprocessors.rst, docs/training.rst, docs/tutorial.rst
Hi, found some typos in the docs as well as in multi_adapter.py. Fixed them, so please have a look.
=> fixed some typos

chatterbot/utils.py
=> Improve NLTK corpus download error message

chatterbot/utils.py, docs/utils.rst, tests/benchmarks.py, tests/test_utils.py
Performance is important. This makes changes to move some of the benchmarking test code into the main chat bot module to make it easier to write and run benchmarking tests.
=> Add performance benchmarking to main module

chatterbot/trainers.py, tests/training_tests/test_ubuntu_corpus_training.py
Fix based on reported issue #755.
=> Open Ubuntu corpus tsv as utf-8

chatterbot/storage/sql_storage.py
=> Create SQL tables if they do not already exist

chatterbot/storage/django_storage.py, tests_django/test_django_adapter.py
Closes #630 #776 #622 #308 #722
=> Correct order responses are saved in

examples/learning_new_response.py
Referring to #753.
Python File added for the same issue that i created, regarding proper implementation of `learning_feedback_example.py`
So I have added a file using the code provided in #753 to learn responses from user.
`learning_new_response.py`
merge is possible ! :D
=> Referring to #753 :learning_new_response.py 

chatterbot/trainers.py, tests/training_tests/test_ubuntu_corpus_training.py
=> Correct file extraction check for Ubuntu dialog corpus

tests/test_turing.py
(This converts a few of the very basic Turing tests that were listed in the project wiki into actual test cases.)
=> Additional tests

.gitignore, chatterbot/trainers.py, tests/training_tests/test_twitter_trainer.py
This pull request is intent to improve training process for larger ``datasets``. 
1. Removed ``statment_history`` in ``UbuntuCorpusTrainer``
2. Ignore ``data`` Ubuntu corpus files dir
3. Import order
=> Remove statment_hsitory from UbuntuCorpus

chatterbot/storage/sql_storage.py
This corrects a few issues regarding conventions for primary keys and unique attributes.
=> Fix setup of primary keys is SQL storage adapter

requirements.txt
=> Add dateutil to the requirements

docs/_includes/python_module_structure.txt, docs/development.rst, docs/packaging.rst
=> Document how to distribute a python module for ChatterBot

examples/basic_example.py
This adds a training step the basic example in the documentation to help avoid possible confusion where someone runs the example and the chat bot doesn't produce a response because it hasn't been trained.
=> Add training to basic example

.travis.yml, MANIFEST.in, dev-requirements.txt, setup.cfg, setup.py, tox.ini
This is an experimental pull request to see how tox performs for tests as opposed to running numerous VM instances on Travis CI. Additionally this would add the benefit of allowing developers to more easily run the full suite of tests that the integration server normally runs.
So far it looks like it also reduces the running time for tests by an average of 10 minutes.
=> Configure tox

examples/django_app/README.rst
=> Fix broken django docs link

dev-requirements.txt
=> Update sphinx to the latest version

chatterbot/adapters.py, chatterbot/chatterbot.py
Fixes the hipchat example by providing a usable backlink of the Chatbot instance to the Adapter instance.
=> Provide chatbot instance to adaptors move up session creation.

chatterbot/chatterbot.py, chatterbot/conversation/statement.py, chatterbot/ext/sqlalchemy_app/models.py, chatterbot/input/input_adapter.py, chatterbot/logic/multi_adapter.py, chatterbot/storage/sql_storage.py
=> Correct a few spelling issues

chatterbot/trainers.py
I think it's nice to have a param to specific tweets language when gathering data from Twitter.
=> Add twitter_lang param to TwitterTrainner

docs/_static/style.css, docs/_templates/footer.html
=> Add newsletter signup for to documentation page

docs/conf.py
(The docs should always be built with the latest local version of the code)
=> Don't install chatterbot from pypi when building docs

chatterbot/logic/time_adapter.py
This adds the ability to pass in custom positive and negative
training data for the NaiveBayesClassifier.
A few new positive and negative data elements have been added.
A first word feature has been added to help identify questions.
Closes #994
=> Time logic adapter improvements

chatterbot/storage/sql_storage.py, requirements.txt
https://docs.sqlalchemy.org/en/latest/changelog/changelog_12.html#change-1.2.0
=> Update SQL Alchemy version

docs/django/wsgi.rst
Fix typo in web service documentation.
=> Fix typo in WSGI

dev-requirements.txt, setup.cfg, tox.ini
=> Use native nose exclude instead of plugin

chatterbot/chatterbot.py, chatterbot/trainers.py, tests/training_tests/test_training_preprocessors.py
=> Use preprocessors during training

tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py, tests/training_tests/test_list_training.py, tests_django/test_django_adapter.py
This pull request introduces test cases, some with expected failures, to be fixed as a part of #1192
These tests are being introduced separately from #1192 so that fixes can be introduced incrementally and potentially worked on in parallel.
=> Add tests with expected failures for #1192

chatterbot/storage/django_storage.py, tests_django/test_django_adapter.py
For #1192
Closes #902
Closes #1134
=> Fix ordering of latest responses in Django adapter

chatterbot/conversation.py
=> Modify dateutil import

examples/basic_example.py
Fixed erroneous comment in basic_example.py
Arises from change made in ae4ad35
=> Fixed misguided comment

docs/tutorial.rst
Added missing indentation in tutorial.rst
=> Added missing indentation

chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, docs/chatterbot.rst, docs/tutorial.rst, examples/mailgun.py, examples/terminal_example.py, examples/terminal_mongo_example.py, examples/tkinter_gui.py, examples/twitter_training_example.py, tests/base_case.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py, tests/test_initialization.py
=> Remove database parameter from storage adapters in favor of database_uri

chatterbot/chatterbot.py, chatterbot/trainers.py, tests/training_tests/test_twitter_trainer.py
=> Require chatbot parameter for training classes

chatterbot/conversation.py, chatterbot/ext/sqlalchemy_app/models.py
=> Add created_at attribute to SQL alchemy model and Statement object

chatterbot/storage/sql_storage.py, tests/base_case.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py
A different create method is going to be added which will be used for creating statements.
(More changes for #1391)
=> Replace SQLStorageAdapter.create with SQLStorageAdapter.create_database

chatterbot/ext/django_chatterbot/management/commands/train.py, docs/testing.rst, examples/django_app/example_app/urls.py, examples/django_app/tests/test_api.py, examples/django_app/tests/test_example.py, setup.py, tox.ini
=> Drop support for Django 1.8 and add support for 2.0

chatterbot/conversation.py, chatterbot/ext/django_chatterbot/abstract_models.py, chatterbot/storage/django_storage.py, chatterbot/storage/sql_storage.py, chatterbot/trainers.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sqlalchemy_adapter.py, tests_django/integration_tests/test_statement_integration.py, tests_django/test_django_adapter.py
This adds tests and makes code changes to ensure that storage adapters add tags to statements when using the `update` function.
=> Make sure all storage adapters update tags

chatterbot/ext/sqlalchemy_app/models.py, chatterbot/storage/sql_storage.py
This change makes it so that similar code lives in consistent places.
=> Move get_statement method to storage adapter to match mongo adapter

README.md
[![Python 3.6](https://img.shields.io/badge/python-3.6-blue.svg)](https://www.python.org/downloads/release/python-360/)
=> README to show supported Python and Django versions 

chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sql_adapter.py, tests_django/test_django_adapter.py
=> Add tests for filtering statements by their tags

chatterbot/trainers.py
This change is so that the existing logger for the ChatBot will be used when training.
=> Use the ChatBot logger when training

chatterbot/comparisons.py, chatterbot/conversation.py, chatterbot/logic/logic_adapter.py, chatterbot/storage/storage_adapter.py, chatterbot/trainers.py, tests/base_case.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/test_comparisons.py, tests/test_examples.py, tests/training_tests/test_ubuntu_corpus_training.py
Closes #1034
Closes #997 
Closes #1377
=> Implement skipped comparison tests

chatterbot/conversation.py, chatterbot/ext/django_chatterbot/abstract_models.py, chatterbot/ext/django_chatterbot/migrations/0016_statement_stemmed_text.py, chatterbot/ext/sqlalchemy_app/models.py
These fields will be used to improve search functionality used for matching.
=> Add fields for statement stemmed text

chatterbot/stemming.py, tests/test_stemming.py
=> Create very simple stemming algorithm

docs/tutorial.rst
Correction in "getting a response from your chat bot" section.
the code is not executing with 'None' in the bracket, hence added 'input()' to get inputs from the user.
optionally added a print statement on next line to show the response from bot.
=> correction in "getting response from bot." section

chatterbot/comparisons.py, chatterbot/conversation.py, chatterbot/ext/django_chatterbot/abstract_models.py, chatterbot/ext/django_chatterbot/migrations/0016_statement_stemmed_text.py, chatterbot/ext/sqlalchemy_app/models.py
=> Provide fields for searching text and in_response_to fields

chatterbot/stemming.py, chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/storage/storage_adapter.py, chatterbot/trainers.py, tests/storage_adapter_tests/test_mongo_adapter.py, tests/storage_adapter_tests/test_sql_adapter.py, tests/training_tests/test_chatterbot_corpus_training.py, tests/training_tests/test_list_training.py, tests/training_tests/test_twitter_trainer.py, tests/training_tests/test_ubuntu_corpus_training.py, tests_django/test_django_adapter.py
=> Save search text for statements

chatterbot/chatterbot.py, chatterbot/conversation.py
This makes a few small changes to clean up and improve the usage of the statement object class.
=> Statement object cleanup

chatterbot/trainers.py
This revises changes made in #1470 
The updated training process completes in the same time as the previous version but has a more predictable process flow and has more efficient memory usage.
=> Alternate between reading and writing processes during ubuntu corpus training

docs/training.rst
=> Show separate file for chatbot and training

chatterbot/chatterbot.py, chatterbot/comparisons.py, chatterbot/logic/logic_adapter.py, chatterbot/stemming.py, chatterbot/utils.py, examples/mailgun.py, examples/math_and_time.py, examples/microsoft_bot.py, examples/specific_response_example.py, examples/sql/memory_sql_example.py, examples/terminal_example.py, examples/terminal_mongo_example.py, examples/tkinter_gui.py, examples/twitter_training_example.py, tests/__init__.py, tests/logic/best_match_integration_tests/test_sentiment_comparison.py, tests/logic/best_match_integration_tests/test_synset_distance.py, tests/test_chatbot.py, tests/test_comparisons.py, tests/test_parsing.py, tests/test_utils.py, tests/training/test_list_training.py
This is intended to simplify the process of retrieving initialization functions from the various classes that have them.
=> Replace get_initialization_functions with a utility method

chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, tests/storage/test_mongo_adapter.py, tests/storage/test_sql_adapter.py, tests_django/test_django_adapter.py
=> Add a persona_not_startswith option to storage filters

tests/storage/test_mongo_adapter.py, tests/storage/test_sql_adapter.py, tests_django/test_django_adapter.py
Also fix any issues caused by this.
=> Fix skipped Mongo DB tests

chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, tests/storage/test_mongo_adapter.py, tests/storage/test_sql_adapter.py, tests_django/test_django_adapter.py
=> Add a filter parameter that allows statements to be excluded by word

examples/learning_feedback_example.py, examples/learning_new_response.py
Just fix some not working examples
=> Fix broken examples

chatterbot/stemming.py, tests/test_stemming.py
This may yield better results in some cases for #1452
=> Add a stemmer that uses part of speech bigrams

chatterbot/storage/django_storage.py, chatterbot/storage/mongodb.py, chatterbot/storage/sql_storage.py, chatterbot/trainers.py, tests/storage/test_mongo_adapter.py, tests/storage/test_sql_adapter.py, tests_django/test_django_adapter.py
This will allow filtering by search_text such that the results returned will match any word in the provided value.
=> Add filter option for search_text_contains

chatterbot/stemming.py, tests/test_stemming.py
A revision to the changes added in #1521
=> Better handle low quality input when creating POS tag bigrams

chatterbot/ext/django_chatterbot/abstract_models.py, chatterbot/ext/django_chatterbot/migrations/0017_tags_unique.py, chatterbot/ext/sqlalchemy_app/models.py, chatterbot/storage/sql_storage.py
Tag names should be unique, not primary keys.
=> Revert pull request #1484

chatterbot/logic/mathematical_evaluation.py, chatterbot/logic/unit_conversion.py, chatterbot/tagging.py
=> Use language parameter in logic adapters

chatterbot/tagging.py, tests/test_tagging.py
=> Add fallbacks for various levels of supported languages

examples/django_app/example_app/templates/nav.html, examples/django_app/requirements.txt
=> Make sure Django tests use correct ChatterBot version

docs/django/index.rst
=> Indicate where INSTALLED_APPS is located

docs/examples.rst
=> Add link from examples to setup instructions

docs/tutorial.rst
=> Change training to trainers in example

chatterbot/chatterbot.py
=> Remove exception checks

chatterbot/chatterbot.py
=> Document parameters for get_response method

chatterbot/chatterbot.py, chatterbot/conversation.py, chatterbot/storage/storage_adapter.py, tests/storage/test_storage_adapter.py
This also closes #904. I'll work on #1097 as I have time to do so.
=> Use serialized input statement in learn_response

README.md, requirements.txt, setup.py, tests/test_corpus.py
This will hopefully improve the process for releasing updates to the data files.
=> Download chatterbot-corpus directly from GitHub

requirements.txt
This adds spacy to the project requirements.
I'm interested in leveraging the performance improvements that it's models offer. This addition to the requirements may end up being removed before the next version is replaced.
=> Add spacy to requirements

chatterbot/chatterbot.py, chatterbot/comparisons.py, chatterbot/tagging.py, chatterbot/utils.py, tests/test_chatbot.py, tests/test_comparisons.py, tests/test_search.py, tests/test_tagging.py
The code for these was previously spread out and duplicated in many locations.
This change removes the duplicates and reduces a bit of complexity.
=> Dry up initialization functions

examples/learning_feedback_example.py
In the older version the feedback was always required, it didn´t matter you replied "yes" or "no", with this version this is fixed and only if you say it´s not a coherent response when you are asked to provide another response.
=> Fix learning_feedback_examply.py

requirements.txt
=> Update sqlalchemy to version >= 1.3

chatterbot/__init__.py
Release 1.2.1 addresses some changes needed to better accommodate the recently updated set of dependencies.
Primarily, I'm drafting this pull request as a way to bulk-close a number of duplicate or related issues that I believe were handled by the previous release (1.2.0).
Primarily all of these are packaging and python version related:
Closes #2381, closes #2378, closes #2285, closes #2286, closes #2295, closes #2297, closes #2303, closes #2305, closes #2304, closes #2310, closes #2314, closes #2319, closes #2317, closes #2325, closes #2330, closes #2331, closes #2335, closes #2337, closes #2338, closes #2339, closes #2343, closes #2344, closes #2349, closes #2357, closes #2372, closes #2043, closes #2057, closes #2063, closes #2066, closes #2080, closes #2081, closes #2082, closes …
=> Update package version for release 1.2.1

chatterbot/logic/specific_response.py, docs/tutorial.rst, docs/tutorials/index.rst, docs/tutorials/tutorial-spacy-rule-based-matching.rst, tests/logic/test_specific_response.py
This adds additional functionality to the `SpecificResponseAdapter` to support:
* Accepting patterns using spaCy's rule-based matching: https://spacy.io/usage/rule-based-matching
* Accepting a function for the `output_text` parameter that can be called to generate the output text.
***
This pull request relates to and closes the following:
* Closes #2242
=> Add more functionality for specific responses

chatterbot/chatterbot.py, chatterbot/comparisons.py, chatterbot/logic/specific_response.py, chatterbot/logic/time_adapter.py, chatterbot/tagging.py, chatterbot/utils.py, docs/chatterbot.rst, docs/comparisons.rst, docs/index.rst, tests/test_chatbot.py
Adds:
* Better documentation for tagging classes
* Improved exceptions messages for missing language models
=> Better document tagging classes

.github/workflows/python-package.yml, chatterbot/ext/sqlalchemy_app/models.py, chatterbot/storage/sql_storage.py, docs/testing.rst, pyproject.toml, setup.cfg, tests/base_case.py, tests/storage/test_mongo_adapter.py, tests/storage/test_redis_adapter.py
This pull request aims to see how easily support for Python versions 3.10, 3.11, 3.12, and 3.13 might be to add.
https://devguide.python.org/versions/
***
* Closes #2379
* Closes #2312
* Closes #2373
* Closes #2243
* Closes #2225
* Helping get closer to 3.13 support (#2402)
=> Add support for Python versions 3.10, 3.11, 3.12

chatterbot/trainers.py
This pull request makes a few changes:
1. It fixes the single file case where a `yield` should be used instead of a `return` - the difference seems to be that the former results in an empty generator evaluation when a single file is provided.
2. Absolute path resolution has been added for easier identification of file locations if the specified file is not found.
3. A more descriptive error message.
=> Fix file path resolution
